#!/bin/bash
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
# calibrate.sh — recapture click coordinates for THIS machine.
#
# Writes messaging_coords.local.sh (git-ignored) next to the helpers. The
# helpers auto-load it, so your captured values override the repo defaults
# WITHOUT touching any tracked file. Delete that file to fall back to defaults.
#
# Usage:  ./calibrate.sh [line|whatsapp|all]      (default: all)
#
# For each item: make sure the app window is pinned the way the scripts expect
# (WhatsApp ~{0,25} 1440×875, LINE ~{0,30} 1440×794 — or your own consistent
# size), hover the mouse over the target, then press Enter. Type "s" to skip an
# item (its default value stays in effect).
#
# Requires cliclick:  brew install cliclick

set -u
DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="$DIR/messaging_coords.local.sh"
WHICH="${1:-all}"

command -v cliclick >/dev/null 2>&1 || {
  echo "❌ 需要 cliclick。請先安裝:brew install cliclick"
  exit 1
}

# Read the current cursor position, echo "x y" (tolerant of cliclick's format).
read_xy() {
  local raw
  raw=$(cliclick p 2>/dev/null)
  local x y
  x=$(printf '%s' "$raw" | grep -oE '[0-9]+' | sed -n 1p)
  y=$(printf '%s' "$raw" | grep -oE '[0-9]+' | sed -n 2p)
  printf '%s %s' "$x" "$y"
}

# grab XVAR YVAR "description" — capture a point (both axes).
grab() {
  local xvar="$1" yvar="$2" desc="$3" ans="" xy x y
  printf '\n>> %s\n' "$desc"
  printf '   滑鼠移到該位置後按 Enter(輸入 s 跳過):'
  read -r ans
  if [ "$ans" = "s" ]; then echo "   ⏭  略過 $xvar/$yvar(維持預設)"; return; fi
  xy=$(read_xy); x=${xy% *}; y=${xy#* }
  if [ -z "$x" ] || [ -z "$y" ]; then echo "   ⚠️  讀不到座標,略過"; return; fi
  printf '%s=%s\n%s=%s\n' "$xvar" "$x" "$yvar" "$y" >> "$OUT"
  printf '   ✓ %s=%s  %s=%s\n' "$xvar" "$x" "$yvar" "$y"
}

# grab1 VAR x|y "description" — capture only one axis (the other is fixed).
grab1() {
  local var="$1" axis="$2" desc="$3" ans="" xy v
  printf '\n>> %s\n' "$desc"
  printf '   滑鼠移到該位置後按 Enter(輸入 s 跳過):'
  read -r ans
  if [ "$ans" = "s" ]; then echo "   ⏭  略過 $var(維持預設)"; return; fi
  xy=$(read_xy)
  if [ "$axis" = "x" ]; then v=${xy% *}; else v=${xy#* }; fi
  if [ -z "$v" ]; then echo "   ⚠️  讀不到座標,略過"; return; fi
  printf '%s=%s\n' "$var" "$v" >> "$OUT"
  printf '   ✓ %s=%s\n' "$var" "$v"
}

# Start a fresh override file.
{
  echo "#!/bin/bash"
  echo "# messaging_coords.local.sh — machine-specific coordinate overrides."
  echo "# Generated by calibrate.sh. Auto-loaded by wa_helpers.sh / line_helpers.sh."
  echo "# Git-ignored. Delete this file to restore the repo's default coordinates."
} > "$OUT"

echo "══════════════════════════════════════════════════════════════"
echo " 座標校準 — 結果寫入:$OUT"
echo " 先把 App 視窗擺到腳本假設的大小(見檔頭),再逐項對準滑鼠。"
echo "══════════════════════════════════════════════════════════════"

if [ "$WHICH" = "whatsapp" ] || [ "$WHICH" = "all" ]; then
  echo ""
  echo "── WhatsApp ──(打開一個聊天室)"
  grab  WA_INPUT_X        WA_INPUT_Y        "訊息輸入框中央"
  grab  WA_CALL_DROPDOWN_X WA_CALL_DROPDOWN_Y "右上角『通話』圖示"
  grab  WA_VOICE_CALL_X   WA_VOICE_CALL_Y   "通話下拉的『語音通話』(請先手動點開通話圖示)"
  grab  WA_VIDEO_CALL_X   WA_VIDEO_CALL_Y   "通話下拉的『視訊通話』"
  grab  WA_ATTACH_X       WA_ATTACH_Y       "輸入列左下『+』附件鈕"
  grab  WA_ATTACH_FILE_X  WA_ATTACH_FILE_Y  "『+』彈出選單的『檔案』項(請先點開 +)"
  grab  WA_PANEL_ROW1_X   WA_PANEL_ROW1_Y   "開檔視窗第一個檔案列(可先開附件 → 檔案)"
  grab  WA_PRIVACY_X      WA_PRIVACY_Y      "隱私 popup 的關閉 X(沒出現就按 s 跳過)"
  grab1 WA_SEARCH_ROW1_Y  y                 "搜尋結果第一列(只取 Y;搜尋一個名字後對準)"
fi

if [ "$WHICH" = "line" ] || [ "$WHICH" = "all" ]; then
  echo ""
  echo "── LINE ──(打開一個聊天室)"
  grab  LINE_RESULT_X     LINE_RESULT_ROW1_Y "搜尋結果第一列(搜尋一個名字後對準)"
  grab  LINE_PHONE_ICON_X LINE_PHONE_ICON_Y  "右上角電話圖示"
  grab  LINE_VOICE_X      LINE_VOICE_Y       "通話下拉的『語音通話』(請先手動點開電話圖示)"
  grab  LINE_VIDEO_X      LINE_VIDEO_Y       "通話下拉的『視訊通話』"
  grab  LINE_ATTACH_X     LINE_ATTACH_Y      "輸入列的附件鈕(+ / 迴紋針)"
  grab  LINE_INPUT_X      LINE_INPUT_Y       "訊息輸入框(LINE 主要靠 AX,此為備援座標)"
fi

echo ""
echo "✅ 完成 → $OUT"
echo "   下次跑 wa_*.sh / line_*.sh 會自動套用這些座標。"
echo "   想還原預設:刪掉這個檔即可。"
echo ""
echo "ℹ️  行高(WA_SEARCH_ROW_HEIGHT / LINE_ROW_H)沒在這裡抓;若你的清單"
echo "   行距不同,手動在上面那個檔加一行,例如:LINE_ROW_H=80"
